default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jwt_backend_development
  username: postgres
  host: localhost
  password: root

test: &test
  <<: *default
  database: jwt_backend_test
  username: postgres
  password: root
  host: localhost

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: jwt_backend_production
  username: postgres
  password: root
  host: localhost
  port: 5432